#!/bin/sh
acg_path="/opt/acg"

# Load Configuration
if [ -f "${acg_path}/files/acg-cfg" ]; then
  . "${acg_path}/files/acg-cfg"
else
  echo "The configuration file is missing. Please re-run the installation script."
  exit 1
fi
# Load Version
. "${acg_path}/files/version"

if [ -z "${BYPASS_CGROUP_CLASSID_AGH}" ]; then
  echo "AdGuard Home is not installed or not properly configured."
  echo "Missing BYPASS_CGROUP_CLASSID_AGH"
  exit 0
fi

${acg_path}/scripts/bypass-proxy-pid-agh $$ 2>&1 > /dev/null

exec "$@"
