#!/bin/ash
acg_path="/opt/acg"

# Load Configuration
if [ -f "${acg_path}/files/acg-cfg" ]; then
  . "${acg_path}/files/acg-cfg"
else
  echo "The configuration file is missing. Please re-run the installation script."
  exit 1
fi
# Load Version
. "${acg_path}/files/version"

${acg_path}/scripts/bypass-proxy-pid $$ 2>&1 > /dev/null

exec "$@"
